# .github/workflows/publish.yml   (in the fork)
name: Docker publish fork
on:
  push: {branches: [main]}        # build when you change the generator
  workflow_dispatch:
permissions: write-all            # needed for GHCR push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')   # lowercase
                IMAGE="ghcr.io/${OWNER_LC}/openapi-generator-cli:latest"

                echo "${{ secrets.GITHUB_TOKEN }}" |
                docker login ghcr.io -u ${{ github.actor }} --password-stdin

                docker build -t "$IMAGE" .
                docker push "$IMAGE"